# Generated by Django 5.2.dev20241023172036 on 2024-10-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
            ],
        ),
    ]
