# Generated by Django 5.2.dev20241023172036 on 2024-10-29 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0004_user_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="mysite.user"
            ),
        ),
    ]
